// <auto-generated />
namespace Optica.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class ContactPatient_et_Medecin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ContactPatient_et_Medecin));
        
        string IMigrationMetadata.Id
        {
            get { return "201504131645166_ContactPatient_et_Medecin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
