// <auto-generated />
namespace Optica.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class AjoutContraintes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AjoutContraintes));
        
        string IMigrationMetadata.Id
        {
            get { return "201504030946379_AjoutContraintes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
