// <auto-generated />
namespace Optica.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class acte_medical_field_obligatoire : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(acte_medical_field_obligatoire));
        
        string IMigrationMetadata.Id
        {
            get { return "201506261659113_acte_medical_field_obligatoire"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
