// <auto-generated />
namespace Optica.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MAJPack_ModifDeStructure_du_BD : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MAJPack_ModifDeStructure_du_BD));
        
        string IMigrationMetadata.Id
        {
            get { return "201505021013043_MAJPack_ModifDeStructure_du_BD"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
